on: [ push, pull_request ]
name: Test
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: fuzz
        run: go test ./...
        working-directory: fuzz
      - name: marshal
        run: go test ./...
        working-directory: marshal
      - name: structs
        run: go test ./...
        working-directory: structs
